REDIS_HOST = 'rj'
REDIS_PORT = 6379

AUTH_SERVER_PROTOCOL = 'http'
AUTH_SERVER_ADDRESS = '127.0.0.1'
AUTH_SERVER_PORT = 8080
AUTH_SERVER_URL = f'{AUTH_SERVER_PROTOCOL}://{AUTH_SERVER_ADDRESS}:{AUTH_SERVER_PORT}'

DB_SERVER_PROTOCOL = 'http'
DB_SERVER_ADDRESS = '127.0.0.1'
DB_SERVER_PORT = 8080
DB_SERVER_URL = f'{DB_SERVER_PROTOCOL}://{DB_SERVER_ADDRESS}:{DB_SERVER_PORT}'

