REDIS_HOST = 'rj'
REDIS_PORT = 6379

AUTH_SERVER_PROTOCOL = 'https'
AUTH_SERVER_ADDRESS = 'ots.prvt.dev'
AUTH_SERVER_PORT = 443
AUTH_SERVER_URL = f'{AUTH_SERVER_PROTOCOL}://{AUTH_SERVER_ADDRESS}:{AUTH_SERVER_PORT}'

DB_SERVER_PROTOCOL = 'https'
DB_SERVER_ADDRESS = 'ots.prvt.dev'
DB_SERVER_PORT = 443
DB_SERVER_URL = f'{DB_SERVER_PROTOCOL}://{DB_SERVER_ADDRESS}:{DB_SERVER_PORT}'

